# Generated by Django 4.0.2 on 2022-03-17 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto5_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativa',
            name='pergunta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projeto5_website.pergunta'),
            preserve_default=False,
        ),
    ]
